export default {
  FETCHING_LIST_MOVIES: "FETCHING_LIST_MOVIES",
  FETCHING_LIST_MOVIES_SUCCESS: "FETCHING_LIST_MOVIES_SUCCESS",
  FETCHING_LIST_MOVIES_FAILED: "FETCHING_LIST_MOVIES_FAILED",
  FETCHING_CURRENT_MOVIE: "FETCHING_CURRENT_MOVIE",
  FETCHING_CURRENT_MOVIE_SUCCESS: "FETCHING_CURRENT_MOVIE_SUCCESS",
  FETCHING_CURRENT_MOVIE_FAILED: "FETCHING_CURRENT_MOVIE_FAILED"
};
